import type { Metadata } from "next"; 
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer"; 
import { WishlistProvider } from "@/Context/WishlistContext";

 

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body> 
        <WishlistProvider>

        <Navbar/>
        <div className="container mx-auto pt-18"> 
            {children} 
        </div>
        
        <Toaster/>
        <Footer/> 
        
        </WishlistProvider>
      </body>
    </html>
  );
}
